// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKm5EGFmFKe9MvshNxpByI4OjLc1J3Jh8',
    appId: '1:744003845143:web:dfde8bb90e6d6239e53052',
    messagingSenderId: '744003845143',
    projectId: 'devdev-5dd74',
    authDomain: 'devdev-5dd74.firebaseapp.com',
    storageBucket: 'devdev-5dd74.appspot.com',
    measurementId: 'G-GQF89VT6MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChorvZJu-dk9awiJGtZ7m1JvMhcSabVWQ',
    appId: '1:744003845143:android:d26db869667d41cbe53052',
    messagingSenderId: '744003845143',
    projectId: 'devdev-5dd74',
    storageBucket: 'devdev-5dd74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJA8qGkG6kBL_nko6Iy9xkoLedRQQDvc',
    appId: '1:744003845143:ios:f93f3d114bc8beefe53052',
    messagingSenderId: '744003845143',
    projectId: 'devdev-5dd74',
    storageBucket: 'devdev-5dd74.appspot.com',
    iosBundleId: 'com.example.devdynamos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJA8qGkG6kBL_nko6Iy9xkoLedRQQDvc',
    appId: '1:744003845143:ios:f93f3d114bc8beefe53052',
    messagingSenderId: '744003845143',
    projectId: 'devdev-5dd74',
    storageBucket: 'devdev-5dd74.appspot.com',
    iosBundleId: 'com.example.devdynamos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKm5EGFmFKe9MvshNxpByI4OjLc1J3Jh8',
    appId: '1:744003845143:web:51f8d060868b90e0e53052',
    messagingSenderId: '744003845143',
    projectId: 'devdev-5dd74',
    authDomain: 'devdev-5dd74.firebaseapp.com',
    storageBucket: 'devdev-5dd74.appspot.com',
    measurementId: 'G-XESP898QFZ',
  );
}
